export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_RESPONSE = 'AUTH_CLEAR_RESPONSE';

export const SIGNUP_SUCCESS ='SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_START = 'SIGNUP_START';

export const ORDER_HISTORY_SUCCESS = 'ORDER_HISTORY_SUCCESS';
export const ORDER_HISTORY_FETCH_START = 'ORDER_HISTORY_FETCH_START';
export const ORDER_USER_AUTH = 'ORDER_USER_AUTH';
export const ORDER_HISTORY_FAILURE = 'ORDER_HISTORY_FAILURE';

export const ORDER_FOOD_SUCCESS = 'ORDER_FOOD_SUCCESS';
export const ORDER_FOOD_FAILURE = 'ORDER_FOOD_FAILURE';
export const ORDER_FOOD_START_FETCH = 'ORDER_FOOD_START_FETCH';

export const GET_MENU_START = 'GET_MENU_START';
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';

export const GET_TOKEN_TO_ORDER = 'GET_TOKEN_TO_ORDER';
export const GET_TOKEN_TO_ORDER_FAILURE = 'GET_TOKEN_TO_ORDER_FAILURE';

export const POST_MENU_SUCCESS = 'POST_MENU_SUCCESS';
export const POST_MENU_ERROR = 'POST_MENU_ERROR';
export const POST_MENU_START = 'POST_MENU_START';

export const ADMIN_MENU_START = 'ADMIN_MENU_START';
export const ADMIN_MENU_FAIL = 'ADMIN_MENU_FAIL';
export const ADMIN_MENU_SUCCESS = 'ADMIN_MENU_SUCCESS';

export const UPDATE_MENU_SUCCESS = 'UPDATE_MENU_SUCCESS';
export const UPDATE_MENU_START = 'UPDATE_MENU_START';
export const UPDATE_MENU_FAILURE = 'UPDATE_MENU_FAILURE';

export const DELETE_MENU_START = 'DELETE_MENU_START';
export const DELETE_MENU_FAILURE = 'DELETE_MENU_FAILURE';
export const DELETE_MENU_SUCCESS = 'DELETE_MENU_SUCCESS';

export const GET_ADMIN = 'GET_ADMIN';
