export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_RESPONSE = 'AUTH_CLEAR_RESPONSE';

export const SIGNUP_SUCCESS ='SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_START = 'SIGNUP_START';

export const ORDER_HISTORY_SUCCESS = 'ORDER_HISTORY_SUCCESS';
export const ORDER_HISTORY_FETCH_START = 'ORDER_HISTORY_FETCH_START';
export const ORDER_USER_AUTH = 'ORDER_USER_AUTH';
export const ORDER_HISTORY_FAILURE = 'ORDER_HISTORY_FAILURE';
